### PR TITLE
Replace node-uuid with uuid

### LINKED ISSUE #108: Replace node-uuid
# Overview
- What project is this issue for?: all
- Is this a bug, security, feature request, or feedback: feature request

## Details

Replace node-uuid to uuid to avoid warning:

screen shot 2017-03-25 at 7 41 20 pm

### PR DESCRIPTION
**Pull request by chrisbodhi**
Replace the deprecated node-uuid module with uuid.

Closes #108

And I've signed the CLA. My email is cboette@gmail.com

Please let me know if you have any questions, comments, or concerns -- thanks!

### CODE REVIEW

**Comment by chrisbodhi** [comment]
Build failed with a timeout:

```
> Install dependencies for broid-flowdock
yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/flowdock/-/flowdock-0.9.1.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/pipeline/source/broid-flowdock/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

And it looks like I'm not authorized to rebuild the project in Wercker.

**Comment by dustinblackman** [comment]
@chrisbodhi Thanks for this! I reran your tests, looks like you're failing lint at the moment. Let me know if you need some help.

**Comment by chrisbodhi** [comment]
@dustinblackman Thanks for catching that! Looks like it's passing now. Let me know if you need anything else.

**Comment by killix** [comment]
Tests pass. Ready to merge ;)

**Pull request merged**
